import { createSlice } from "@reduxjs/toolkit";


const initialState = {
  origin: null,
  destination: null,
  travelTimeInformation: null, // time it takes to get from origin to destination
};

const navSlice = createSlice({
  name: "nav",
  initialState,
  reducers: {
	// Pretty self explanatory.
	setOrigin: (state, action) => {
		state.origin = action.payload;
	},
	setDestination: (state, action) => {
		state.destination = action.payload;
	},
	setTravelTimeInformation: (state, action) => {
		state.travelTimeInformation = action.payload;
	}
  },
});

// Exporting the actions generated by createSlice for use in components
export const { setOrigin, setDestination, setTravelTimeInformation } = navSlice.actions;

// Exporting the selectors generated by createSlice for use in components
export const { selectOrigin, selectDestination, selectTravelTimeInformation } = navSlice.actions;

// Export the reducer to be included in the Redux store
export default navSlice.reducer;
