export const MODAL_BODY_TYPES = Object.freeze({
  USER_DETAIL: 'USER_DETAIL',
  LEAD_ADD_NEW: 'LEAD_ADD_NEW',
  CONFIRMATION: 'CONFIRMATION',
  DEFAULT: '',
});

export const RIGHT_DRAWER_TYPES = Object.freeze({
  NOTIFICATION: 'NOTIFICATION',
  CALENDAR_EVENTS: 'CALENDAR_EVENTS',
});

export const CONFIRMATION_MODAL_CLOSE_TYPES = Object.freeze({
  LEAD_DELETE: 'LEAD_DELETE',
});
